replicaCount: 1

image:
#  image: "cumulusprod/cirrocumulus:latest"
#  port: 5000
#  command: ["cirro"]
#  args: ["launch", "/data/dataset1.h5ad", "--host", "0.0.0.0"]
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# TODO: Leo sets up the KSA with Workload Identity manually, may want to move to the chart
serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    #  nginx.ingress.kubernetes.io/auth-tls-secret: "{{ $.Release.Namespace }}/ca-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/proxy-redirect-from: "https://k8s-host"
    # nginx.ingress.kubernetes.io/proxy-redirect-to: "https://leo-host"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  #hosts:
  #  - host: "k8s-host"
  #    paths: 
  #      - "/proxy/google/v1/apps/project/app-name/service-name(/|$)(.*)"
  tls:
    - secretName: "tls-secret"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
  # cloud.google.com/gke-nodepool: "nodepool-name"

tolerations: []

affinity: {}

persistence:
  enabled: true 
  storageClass: "manual"
  # size: 50G
  # accessMode: ReadOnlyMany 
  # gcePersistentDisk: "gce-pd-name"
  # mountPath: "/data"

