name: rstudio 
author: workbench-interactive-analysis@broadinstitute.org
description: |
  RStudio
version: 0.0.10
services:
  rstudio:
    # image: "bioconductor/bioconductor_docker:RELEASE_3_15"
    image: "us.gcr.io/broad-dsp-gcr-public/anvil-rstudio-bioconductor:3.15.3"
    port: 8787
    # inject a sed command to remove the www-address config used by Leo
    command:  ["/bin/sh", "-c"]
    args: ["chown -R rstudio:rstudio /home/rstudio && /init"]
    pdMountPath: "/home/rstudio"
    pdAccessMode: "ReadWriteMany"
    environment:
      USER: "rstudio"
      # USERID: "1002"
      PASSWORD: "rstudio"
      DISABLE_AUTH: "true"
