name: rstudio 
author: workbench-interactive-analysis@broadinstitute.org
description: |
  RStudio
version: 0.0.10
services:
  rstudio:
    image: "us.gcr.io/broad-dsp-gcr-public/anvil-rstudio-bioconductor:3.15.3"
    port: 8001
    # inject a sed command to remove the www-address config used by Leo
    command:  ["/bin/sh", "-c"]
    args: ["chown -R rstudio:users /home/rstudio && /init"]
    pdMountPath: "/home/rstudio"
    pdAccessMode: "ReadWriteOnce"
    environment:
      WORKSPACE_NAME: "my-ws"
      WORKSPACE_NAMESPACE: "my-proj"
      # needed to disable auth
      # USER: "rstudio"
      # USERID: "1002"
      # DEFAULT_USER: "rstudio"
      PASSWORD: "changeme"
      DISABLE_AUTH: "true"
