name: rstudio 
author: workbench-interactive-analysis@broadinstitute.org
description: |
  RStudio
version: 0.0.10
services:
  rstudio:
    image: "us.gcr.io/broad-dsp-gcr-public/anvil-rstudio-bioconductor:3.15.3"
    port: 8787
    command:  ["/bin/sh", "-c"]
    args: ["chown -R rstudio:users /home/rstudio && /init"]
    pdMountPath: "/home/rstudio"
    pdAccessMode: "ReadWriteOnce"
    environment:
      # needed to disable auth
      DISABLE_AUTH: "true"
