name: jupyter 
author: foo@broadinstitute.org
description: |
  Jupyter Notebook
version: 0.0.1
services:
  cirrocumulus:
    image: "jupyter/datascience-notebook:9b06df75e445"
    port: 8888
    command:  []
    args: []
    pdMountPath: "/data"
    pdAccessMode: "ReadWriteOnce"
    environment: []
