name: jupyter 
author: workbench-interactive-analysis@broadinstitute.org
description: |
  Jupyter
version: 1.0.14
services:
  rstudio:
    image: "us.gcr.io/broad-dsp-gcr-public/terra-jupyter-gatk:1.0.14"
    port: 8000
    # inject a sed command to strip out path customizations used by Leo; this causes the app to listen on /
    command:  ["/bin/sh", "-c"]
    args: ["sed -i 's/^c.NotebookApp.base_url.*$//; s/^.*static_url_prefix.*$//' $JUPYTER_HOME/jupyter_notebook_config.py && /usr/local/bin/jupyter notebook"]
    pdMountPath: "/data"
    pdAccessMode: "ReadWriteOnce"
    environment:
      WORKSPACE_NAME: "my-ws"
      WORKSPACE_NAMESPACE: "my-proj"
