replicaCount: 1

# Provided by the app descriptor
image:
  image: "gcr.io/cryptic-skyline-320001/terra-rstudio-aou:smoke-test-1"
  port: 8787
  baseUrl: /
  args: ["chown -R rstudio:users /home/rstudio && /init_aou"]
  command: ["/bin/sh", "-c"]
  pullPolicy: IfNotPresent

# Provided by Leonardo
configs: {}
# WORKSPACE_NAME: my-ws

# Provided by Leonardo
extraEnv:
# - name: WORKSPACE_NAME
#   value: my-workspace

imagePullSecrets: []
nameOverride: aou-rstudio
fullnameOverride: ""

# Provided by Leonardo
serviceAccount:
  name: "test-service-account"

podAnnotations: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80

# TLS and rewrite rules provided by Leonardo
ingress:
  enabled: true
  annotations:
  # nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
  # nginx.ingress.kubernetes.io/auth-tls-secret: "{{ $.Release.Namespace }}/ca-secret"
  # nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
  # nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # nginx.ingress.kubernetes.io/proxy-redirect-from: "https://k8s-host/"
  # nginx.ingress.kubernetes.io/proxy-redirect-to: "https://leo-host/"
  # nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  hosts:
    - host: "k8s.app.info"
      paths:
        - "/app(/|$)(.*)"
  # tls:
  # - secretName: "tls-secret"
  #   hosts:
  #     - "k8s.app.info"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Provided by Leonardo
nodeSelector: {}
# cloud.google.com/gke-nodepool: "nodepool-name"

tolerations: []

affinity: {}

# either GCE PD provided by Leonardo; or hostPath provided by terra-docker-local.sh
persistence:
  enabled: true
  storageClass: "manual"
  size: 100G
  accessMode: ReadWriteMany
  gcePersistentDisk: "disk--test"
  # hostPath: "/data"
  mountPath: "/home/rstudio"

welder:
  extraEnv:
  - name: GOOGLE_PROJECT
    value: "cryptic-skyline-320001"
  - name: STAGING_BUCKET
    value: "aou-startup-script"
  - name: SHOULD_BACKGROUND_SYNC
    value: true
  - name: CLUSTER_NAME
    value: "all-of-us-123"
  - name: RUNTIME_NAME
    value:  "all-of-us-123"
  - name: OWNER_EMAIL
    value: "yonghaotest1@gmail.com"
  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi