{{- if .Values.configs }}
apiVersion: v1
metadata:
  name: {{ include "app.fullname" . }}-configs
  labels:
    {{- include "app.labels" . | nindent 4 }}
kind: ConfigMap
data:
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry -}}
  {{- $key | nindent 4 }}: |
    {{- $entry | print | nindent 8 }}
  {{- end -}}
  {{- end }}
---
{{- end -}}
