apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{- .Values.serviceAccount.name }}"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "app.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-pvc
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command:
            {{- range .Values.image.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.image.args }}
          args: 
            {{- range .Values.image.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.extraEnv }}
          env:
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }} 
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: "{{ .Values.persistence.mountPath -}}"
              name: {{ include "app.fullname" . }}-storage
          livenessProbe:
            httpGet:
              path: "{{ .Values.image.baseUrl }}"
              port: http
          readinessProbe:
            httpGet:
              path: "{{ .Values.image.baseUrl }}"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: welder
          image: "us.gcr.io/broad-dsp-gcr-public/welder-server"
          env:
            - name: GOOGLE_PROJECT
              value: "${GOOGLE_PROJECT}"
            - name: STAGING_BUCKET
              value: "${STAGING_BUCKET}"
            - name: CLUSTER_NAME
              value: "${RUNTIME_NAME}"
            - name: RUNTIME_NAME
              value: ${RUNTIME_NAME}"
            - name: OWNER_EMAIL
              value: "${OWNER_EMAIL}"
            - name: IS_RSTUDIO_RUNTIME
              value: "${IS_RSTUDIO_RUNTIME}"
            - name: CLOUD_PROVIDER
              value: "gcp"
            - name: LOCKING_ENABLED
              value: "true"
            - name: PORT
              value: "8080"
            - name: WSM_URL
              value: "dummy"
            - name: WORKSPACE_ID
              value: "dummy"
            - name: STORAGE_CONTAINER_RESOURCE_ID
              value: "dummy"
            - name: STAGING_STORAGE_CONTAINER_RESOURCE_ID
              value: "dummy"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
