apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{- .Values.serviceAccount.name }}"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "app.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-pvc
      containers:
        - name: aou-rstudio
          image: "{{ .Values.image.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          command:
            {{- range .Values.image.command }}
            - {{ . | quote }}
            {{- end }}
          args:
            {{- range .Values.image.args }}
            - {{ . | quote }}
            {{- end }}
          env:
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8787
              protocol: TCP
          volumeMounts:
            - mountPath: "{{ .Values.persistence.mountPath -}}"
              name: {{ include "app.fullname" . }}-storage
          livenessProbe:
            httpGet:
              path: "{{ .Values.image.baseUrl }}"
              port: http
          readinessProbe:
            httpGet:
              path: "{{ .Values.image.baseUrl }}"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: welder
          image: "us.gcr.io/broad-dsp-gcr-public/welder-server:6648f5c"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: CLOUD_PROVIDER
              value: "gcp"
            - name: LOCKING_ENABLED
              value: "true"
            - name: SHOULD_BACKGROUND_SYNC
              value: "true"
            - name: WSM_URL
              value: "dummy"
            - name: WORKSPACE_ID
              value: "dummy"
            - name: STORAGE_CONTAINER_RESOURCE_ID
              value: "dummy"
            - name: STAGING_STORAGE_CONTAINER_RESOURCE_ID
              value: "dummy"
            - name: PORT
              value: "8080"
#            - name: GOOGLE_PROJECT
#              value: "leo provided"
#            - name: STAGING_BUCKET
#              value: "leo provided"
#            - name: SHOULD_BACKGROUND_SYNC
#              value: "leo provided"
#            - name: CLUSTER_NAME
#              value:"leo provided"
#            - name: RUNTIME_NAME
#              value: "leo provided"
#            - name: OWNER_EMAIL
#              value: "leo provided"
            {{- range .Values.welder.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: welder-http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "{{ .Values.persistence.welderMountPath -}}"
              name: {{ include "app.fullname" . }}-storage
          resources:
            {{- toYaml .Values.welder.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
