{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.fullname" . }}-pv
spec:
  storageClassName: "default"
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany

  claimRef:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "app.fullname" . }}-pvc
  {{- if .Values.persistence.gcePersistentDisk }}
  gcePersistentDisk:
    pdName: {{ .Values.persistence.gcePersistentDisk }}
    fsType: ext4
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-pvc
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  volumeName: {{ include "app.fullname" . }}-pv
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
