apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-welder
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: welder-http
      protocol: TCP
      name: welder-http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
