name: libraoffice
author: workbench-interactive-analysis@broadinstitute.org
description: |
  libraOffice
version: 0.0.1
services:
  rstudio:
    image: "linuxserver/libreoffice:latest"
    port: 8001
    # inject a sed command to remove the www-address config used by Leo
    pdMountPath: "/config"
    pdAccessMode: "ReadWriteOnce"
    environment:
      PUID: "1000"
      PGID: "1000"
