apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress-from-other-namespaces
  namespace: {{ .Release.Namespace  }}
spec:
  podSelector:
    matchLabels:
  ingress:
  {{- if eq .Values.cloud "gcp" -}}
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          name: nginx
  {{- else -}}
  - {}
  {{- end -}}
  egress:
  - {}
  policyTypes:
  - Egress