{{- if eq .Values.cloud "azure" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-relaylistener-depl
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        leoServiceName: relay-listener
    spec:
      containers:
        - name: relaylistener
          image: {{ .Values.relaylistener.image }}
          ports:
            - containerPort: {{ .Values.relaylistener.port }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: LISTENER_RELAYCONNECTIONSTRING
              value: {{ .Values.relaylistener.connectionString }}
            - name: LISTENER_RELAYCONNECTIONNAME
              value: {{ .Values.relaylistener.connectionName }}
            - name: LISTENER_TARGETPROPERTIES_TARGETHOST
              value: {{ .Values.relaylistener.targetHost }}
            - name: LISTENER_TARGETPROPERTIES_REMOVEENTITYPATHFROMHTTPURL
              value: {{ .Values.relaylistener.removeEntityPathFromHttpUrl }}
            - name: LISTENER_REQUESTINSPECTORS
              value: "SAM_CHECKER"
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMURL
              value: {{ .Values.relaylistener.samUrl }}
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMRESOURCEID
              value: {{ .Values.relaylistener.samResourceId }}
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMRESOURCETYPE
              value: {{ .Values.relaylistener.samResourceType }}
            - name: LISTENER_SAMINSPECTORPROPERTIES_SAMACTION
              value: {{ .Values.relaylistener.samAction }}
            - name: LISTENER_SETDATEACCESSEDINSPECTORPROPERTIES_SERVICEHOST
              value: {{ .Values.relaylistener.leoUrl }}
            - name: LISTENER_SETDATEACCESSEDINSPECTORPROPERTIES_WORKSPACEID
              value: {{ .Values.relaylistener.workspaceId }}
            - name: LISTENER_SETDATEACCESSEDINSPECTORPROPERTIES_RUNTIMENAME
              value: {{ .Values.relaylistener.runtimeName }}
            - name: LISTENER_CORSSUPPORTPROPERTIES_VALIDHOSTS
              value: {{ join "," .Values.relaylistener.validHosts }}
      imagePullSecrets:
        - name: acr-secret
{{- end -}}
