apiVersion: v1
kind: Secret
metadata:
  name: "ca-secret"
type: Opaque
data:
{{ (.Files.Glob "ca.crt").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "tls-secret"
type: Opaque
data:
{{ (.Files.Glob "tls.crt").AsSecrets | indent 2 }}
{{ (.Files.Glob "tls.key").AsSecrets | indent 2 }}
