apiVersion: v1
kind: Secret
metadata:
  name: "ca-secret"
type: Opaque
data:
  ca.crt: |-
    {{ .Files.Get "/etc/rootCA.pem" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "tls-secret"
type: Opaque
data:
  tls.crt: |-
    {{ .Files.Get "/etc/jupyter-server.crt" }}
  tls.key: |-
    {{ .Files.Get "/etc/jupyter-server.key" }}
