{{- if eq .Values.cloud "gcp" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "test-service-account"
  labels:
    leonardo: "true"
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.annotations.gcpServiceAccount | quote }}
{{- end -}}