name: rstudio 
author: workbench-interactive-analysis@broadinstitute.org
description: |
  RStudio
version: 0.0.10
services:
  rstudio:
    image: "gcr.io/cryptic-skyline-320001/terra-rstudio-aou:smoke-test-1"
    port: 8787
    command:  ["/bin/sh", "-c"]
    args: ["chown -R rstudio:users /home/rstudio && /init_aou"]
    pdMountPath: "/home/rstudio"
    pdAccessMode: "ReadWriteOnce"
    environment:
      # needed to disable auth
      DISABLE_AUTH: "true"
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]

