# This is a basic workflow to help you get started with Actions
name: App Smoke Test
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # add new apps to be smoke tested to the array below
       app: [jupyter] #,ucsc_genome_browser
    env:
      APP_NAME: ${{ matrix.app }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup data for tests and perform system installs
        run: |
          mkdir test-dir
          touch ./test-dir/temp.txt
          sudo apt-get install jq
          sudo snap install helm --classic
          sudo snap install yq

      # we currently use this pre-made action for minikube https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
      # it supports our use case at the time if writing, but there may come a time when we want to set it up ourselves
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: how do i use a variable for this? do we need to do this in the shell? 
          start args: 'start --vm=true' #--mount --mount-string="./test-dir:/data"
          
      - name: Run smoke test on app 
        run: ./test/smoke-test.sh $APP_NAME

# TODO: the below works and is relevant, we should aim to move away from minikube plugin
      # - name: Install minikube test
      #   run: |
      #     curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm64
      #     sudo install minikube-linux-arm64 /usr/local/bin/minikube
      #     which minikube

