# This is a basic workflow to help you get started with Actions
name: App Smoke Test
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
       app: [ucsc_genome_browser]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup data for tests and perform system installs
        run: |
          mkdir /test-dir
          touch /test-dir/temp.txt
          sudo apt-get install helm

      # we currently use this pre-made action for minikube https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
      # it supports our use case at the time if writing, but there may come a time when we want to set it up ourselves
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: 'start --vm=true --mount --mount-string="/test-dir:/data"'
        
      - name: Interact with the cluster
        env:
          APP_DIR_NAME: ${{ matrix.app }}
        run: |
          echo "app descriptor is: $APP_DIR_NAME"
          kubectl get nodes 
          ./terra-app-local.sh install -f ./apps/$APP_DIR_NAME/app.yaml
          
      - name: Run local app 
        run:
            echo test

