# This is a basic workflow to help you get started with Actions
name: App Smoke Test
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      # means we do not want a failure in a single app's smoketest to cause others to fail. Can be changed
      fail-fast: false
      # add new apps to be smoke tested to the array below
      matrix:
       app: [jupyter, ucsc-genome-browser]
    env:
      APP_NAME: ${{ matrix.app }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup data for tests and perform system installs
        run: |
          sudo apt-get install jq
          sudo snap install helm --classic
          sudo snap install yq

      # # TODO: the below works and is relevant, we should aim to move away from minikube plugin
      # - name: Install and start minikube
      #   run: |
      #     curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
      #     chmod +x minikube
      #     sudo mkdir -p /usr/local/bin/
      #     sudo install minikube /usr/local/bin/
      #     which minikube
      #     MINIKUBE_ARGS=$(jq -r --arg key1 "$APP_NAME" '.[$key1]."minikube-args"' < ci-config.json)
      #     echo "Starting minikube with args: $MINIKUBE_ARGS"

    # minikube start $MINIKUBE_ARGS
      - name: Get Minikube args
        run: |
          echo ::set-env name=MINIKUBE_ARGS::$(jq -r --arg key1 "$APP_NAME" '.[$key1]."minikube-args"' < ci-config.json)'
      # we currently use this pre-made action for minikube https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
      # it supports our use case at the time of writing, but there may come a time when we want to set it up ourselves
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: how do i use a variable for this? do we need to do this in the shell? 
          start args: ${{ env.MINIKUBE_ARGS }}
          
      - name: Run smoke test on app 
        run: |
          sudo echo "$(minikube ip) $(jq -r .hostname < ci-config.json)" | sudo tee -a /etc/hosts
          ./test/smoke-test.sh $APP_NAME

